### ISSUE TITLE
Sotilas

### ISSUE THREAD

**Issue by KasperiA** [KasperiA/Shakkipeli#10]
Nappulan korotus puuttuu

**Comment by KasperiA** [comment]
Joku ihme bugi, että jos vastaavan rivin valkoinen nappula on siirretty jo 2 eteenpäin, niin mustaa ei voi siirtää 2 eteenpäin

**Comment by KasperiA** [comment]
Mustien välinappula -1 vaihto +1 ja valkoisten +1 vaihto -1

**Comment by teemuki3** [comment]
fix'd
