### ISSUE TITLE
Indeksionkelma

### ISSUE THREAD

**Issue by teemuki3** [KasperiA/Shakkipeli#11]
https://github.com/KasperiA/Shakkipeli/blob/13afc323ad653aae9cddd0958c7f1d5d573adb54/Shakkipeli/src/Shakkipeli.java#L56

viittaa indeksit väärin ton numero-osan suhteen

**Comment by KasperiA** [comment]
laittaa ton parsen jälkee -1 ni sitten osuu oikeeseen

**Comment by teemuki3** [comment]
fix 'd
