### ISSUE TITLE
Shakkipeli

### ISSUE THREAD

**Issue by KasperiA** [KasperiA/Shakkipeli#14]
https://github.com/KasperiA/Shakkipeli/blob/5f9dd5762882d23216ecd09885074ada5b634c49/Shakkipeli/src/Shakkipeli.java#L17-L25

Mikä tän idea oli?  Toimii kun on kommentoitu pois, jos ei ole kommentoitu pois, niin ei toimi

**Comment by teemuki3** [comment]
Ensimmäisellä kommentoidulla rivillä on ensimmäinen kirjain väärää kirjainkokoa
