### ISSUE TITLE
Kuningas

### ISSUE THREAD

**Issue by KasperiA** [KasperiA/Shakkipeli#16]
1. Pitää tarkistaa että uhkaako joku tätä nappulaa, jos uhkaa niin tilanne täytyy korjata muita ei saa siirtää, ellei poista uhkaamista
2. ei saa siirtää toisen  kuninkaan viereen
3. eka siirto pitää toteuttaa

Kohtia 1 ja 2 ei välttämättä toteuteta, koska pelin logiikkaa ei tarvinnut toteuttaa

**Comment by teemuki3** [comment]
Mikä on eka siirto?
