### ISSUE TITLE
Tornitus

### ISSUE THREAD

**Issue by KasperiA** [KasperiA/Shakkipeli#8]
Ei voi tehdä jos kuningasta tai tornia on aikaisemmin siirretty tällä hetkellä voi

**Comment by KasperiA** [comment]
Myöskin täytyy tarkistaa, että kuningas ei joudu uhatuksi tornituksen jälkeen

**Comment by KasperiA** [comment]
Eikä kuningas voi ylittää uhattua ruutua

**Comment by teemuki3** [comment]
toi eka asia ois mahdollista toteuttaa jos tekis aika tavalla lisää ylimääräisiä toimintoja ja työtä

**Comment by teemuki3** [comment]
noi 2 vikaa vaatis jo sit niin helkutisti etten oikeen nää et kannattais lähtee

**Comment by teemuki3** [comment]
tai mikäs siinä jos innostaa tehdä :D

**Comment by KasperiA** [comment]
eka on vaa yks muuttuja,
toka on muutenki pakko toteuttaa, muute on toimimaton kuningas nappula,
ja kolmas menee siinä samalla
